Intro which points to Biden Executive Order
ietf-rats/draft-voit-rats-attestation-results pull request #3
Opened 2021-06-02 20:22 UTC by ericvoit

Per Henk's suggestion to change name and link to Biden's Executive Order

2021-06-04 16:55 UTC, henkbirkholz approved these changes
Captures the intent well!

2021-06-07 11:16 UTC, thomas-fossati requested changes
Just a couple of typographical nits, which however are needed to make the source compile.

Also, at L73 the `802.1AR` label should not start with a number.  Maybe prepend `IEEE-` to it.

2021-06-07 11:16 UTC, thomas-fossati commented on draft-voit-rats-attestation-results.md
> +  US Executive Order:
I don't think Carsten's kdrfc likes empty spaces

```suggestion
  US-Executive-Order:
```

2021-06-07 11:16 UTC, thomas-fossati commented on draft-voit-rats-attestation-results.md
> +The first paragraph of the May 2021 US Presidential Executive Order on Improving the Nation's Cybersecurity {{US Executive Order}} ends with the statement "the trust we place in our digital infrastru
```suggestion
The first paragraph of the May 2021 US Presidential Executive Order on Improving the Nation's Cybersecurity {{US- Executive-Order}} ends with the statement "the trust we place in our digital infrastructure should be proportional to how trustworthy and transparent that infrastructure is."  
```

2021-06-09 17:49 UTC, ericvoit commented
Ending comments with new version 01

2021-06-09 17:49 UTC, closed without merging